### ISSUE TITLE
Merge documentation into unified repository

### ISSUE THREAD

**Issue by mbaudis** [mrueda/beacon-schema-2#1]
As per various discussions, it makes sense to merge the documentation together with the framework and models into a unified repository. We have started with one at currently [beacon-v2-unity-testing](https://github.com/ga4gh-beacon/beacon-v2-unity-testing/) (to be renamed when mature...).

My suggestion for the documentation would be to  adjust the tooling to:

* adopt the generated schemas from there as input for the documentation tables
* merge the `docs` and `bin` ... into the unified repo
* adjust the RTD generation 

The time point here could be either ASAP (so contributors directly start at the new location) or at a later "officially move everything" point.

**Comment by mrueda** [comment]
Hi Michael. For this, I would wait for the merge until there is an agreement on proceeding with the [beacon-v2-unity-testing](https://github.com/ga4gh-beacon/beacon-v2-unity-testing/).

Thanks,

Manu

**Comment by mbaudis** [comment]
Done - documentation now there ...
